### PR TITLE
Add missing `protocol`-components for device-roaming-status-subscriptions

### LINKED ISSUE #207: [Device-Roaming-Subscription]: Protocol components are missing in specification
**Describe the bug**
The components described in the `descriminator` for the `prototocol`-property are missing.
This causes problems with our code-generator and makes it unpossible to create the expected property-models.

See:
```yaml
      discriminator:
        propertyName: protocol
        mapping:
          HTTP: "#/components/schemas/HTTPSubscriptionRequest"
          MQTT3: "#/components/schemas/MQTTSubscriptionRequest"
          MQTT5: "#/components/schemas/MQTTSubscriptionRequest"
          AMQP: "#/components/schemas/AMQPSubscriptionRequest"
          NATS: "#/components/schemas/NATSSubscriptionRequest"
          KAFKA: "#/components/schemas/ApacheKafkaSubscriptionRequest"
```
Tested with [r1.2 - device-roaming-status-subscriptions.yaml](https://github.com/camaraproject/DeviceStatus/blob/r1.2/code/API_definitions/device-roaming-status-subscriptions.yaml)
**Expected behavior**
The components should be there, otherwise the yaml is invalid.

### PR DESCRIPTION
**Pull request by maxl2287**
#### What type of PR is this?

Add one of the following kinds:
* bug

#### What this PR does / why we need it:
This PR adds the missing components, which were referenced in the `protocol`-discriminator

#### Which issue(s) this PR fixes:

Fixes #207

### CODE REVIEW

**Review by bigludo7 — APPROVED** [review]
LGTM

**Review by sachinvodafone — APPROVED** [review]

**Review by akoshunyadi — APPROVED** [review]

**Review by akoshunyadi — CHANGES_REQUESTED** [review]
Sorry, just forgot about it. The first change after 0.6.0 should set the version back to wip.

**Review by bigludo7 — APPROVED** [review]
LGTM

**Comment by akoshunyadi** [comment]
@maxl2287 now you set the version for all of the APIs to wip. I think generally it is not necessary, because it is possible that an API remains unchanged in the upcoming version, so only the changed API should be set to wip and later for the release to the new version. Of course we could set the previous version again, if there was no change... Anyway, let's keep it for now.

**Review by akoshunyadi — APPROVED** [review]

**Review by eric-murray — APPROVED** [review]

**Pull request merged**
