### PR TITLE
feat: use simple String for "type" in CloudEvent

### LINKED ISSUE #107: Use simple string for "type" in CloudEvent
**Problem description**
I am looking from a developer POV and we are using code-generators to generate the code based on the CAMARA specifications.
When generating enums, e.g. here SubscriptionEventType, they will be generated like

```java
  ROAMING_STATUS("org.camaraproject.device-status.v0.roaming-status"),
  
  ROAMING_ON("org.camaraproject.device-status.v0.roaming-on"),
  
  ROAMING_OFF("org.camaraproject.device-status.v0.roaming-off"),

  ....
```

The in the spec described enums cannot be used in the CloudEvent, as we want here the String (e.g. org.camaraproject.device-status.v0.roaming-status).

```yaml
    SubscriptionEventType:
      type: string
      description: |
        roaming-status - Event triggered when the device switch from roaming ON to roaming OFF and conversely

        roaming-on - Event triggered when the device switch from roaming OFF to roaming ON

        roaming-off - Event triggered when the device switch from roaming ON to roaming OFF

        roaming-change-country - Event triggered when the device in roaming change country code

        connectivity-data - Event triggered when the device is connected to the network for Data usage.

        connectivity-sms - Event triggered when the device is connected to the network for SMS usage

        connectivity-disconnected - Event triggered when the device is not connected.

        subscription-ends - Event triggered when the subscription is terminated
      enum:
        - org.camaraproject.device-status.v0.roaming-status
        - org.camaraproject.device-status.v0.roaming-on
        - org.camaraproject.device-status.v0.roaming-off
        - org.camaraproject.device-status.v0.roaming-change-country
        - org.camaraproject.device-status.v0.connectivity-data
        - org.camaraproject.device-status.v0.connectivity-sms
        - org.camaraproject.device-status.v0.connectivity-disconnected
        - org.camaraproject.device-status.v0.subscription-ends

    CloudEvent:
      <...>
      properties:
       <...>
        type:
          $ref: "#/components/schemas/SubscriptionEventType"
```

**Possible evolution**
With this change we are not forced anymore to provide a Enum (e.g. ROAMING_STATUS), but can use the value of this enum (e.g. org.camaraproject.device-status.v0.roaming-status)

```yaml
        type:
          type: string
          description: Specifies the type of event for which the event will be sent.
```

### PR DESCRIPTION
**Pull request by maxl2287**
#### What type of PR is this?

Add one of the following kinds:
* enhancement/feature

#### What this PR does / why we need it:
Uses a simple string for the "type" property in CloudEvent instead of an enum.

#### Which issue(s) this PR fixes:

Fixes #107

### CODE REVIEW

**Comment by bigludo7** [comment]
Hello @maxl2287 
Why removing the enum for SubscriptionEventType ?

We have still it in Device Location:

```    
    SubscriptionEventType:
      type: string
      description: |
        area-entered - Event triggered when the device enters the given area
        
        area-left - Event triggered when the device leaves the given area
      enum:
        - org.camaraproject.geofencing.v0.area-entered
        - org.camaraproject.geofencing.v0.area-left
```

**Comment by maxl2287** [comment]
> Hello @maxl2287 Why removing the enum for SubscriptionEventType ?
> 
> We have still it in Device Location:
> 
> ```
>     SubscriptionEventType:
>       type: string
>       description: |
>         area-entered - Event triggered when the device enters the given area
>         
>         area-left - Event triggered when the device leaves the given area
>       enum:
>         - org.camaraproject.geofencing.v0.area-entered
>         - org.camaraproject.geofencing.v0.area-left
> ```

As it is then never used in the document anymore.

Also in DeviceLocation (geofencing), you can see that this component is not used.

**Comment by maxl2287** [comment]
I see that we just use this additional SubscriptionEventType here (and NotificationEventType in geofencing) because of the "subscription-ends".

But this is causing us problems when we have a reference to an enum in CloudEvent

**Comment by bigludo7** [comment]
> I see that we just use this additional SubscriptionEventType here (and NotificationEventType in geofencing) because of the "subscription-ends".
> 
> But this is causing us problems when we have a reference to an enum in CloudEvent

This is used in the yaml.

I get your point about alignement with CloudEvents standard but we probably need a discussion at Commonalities level because it impacts all API with notification.

**Comment by akoshunyadi** [comment]
In Geofencing there is a typo
 type:
          $ref: "#/components/schemas/**Subcription**EventType"

**Comment by maxl2287** [comment]
> In Geofencing there is a typo type: $ref: "#/components/schemas/**Subcription**EventType"

@akoshunyadi I made a fix about that in https://github.com/camaraproject/DeviceLocation/pull/149

**Comment by maxl2287** [comment]
Closed as the commonalities-issue is closed.

**Pull request closed without merging**
