### PR TITLE
Fix Typo in response of CountryName & File name

### PR DESCRIPTION
**Pull request by ravindrapalaskar17**
1. Fix typo in Response of country Name
2. Update the file name to> device-status.yaml

### CODE REVIEW

**Comment by ravindrapalaskar17** [comment]
This PR is for fix the issue--> https://github.com/camaraproject/DeviceStatus/issues/27
@monamok @eric-murray  please review

**Comment by monamok** [comment]
Thank you @ravindrapalaskar17.

**Comment by eric-murray** [comment]
@ravindrapalaskar17
An empty array is really `[]`, not `[ ]`. As we are specifying the response and ideally all implementations will give the same response, it is probably better to be pedantic, so I made the change.

**Comment by ravindrapalaskar17** [comment]
> @ravindrapalaskar17 An empty array is really `[]`, not `[ ]`. As we are specifying the response and ideally all implementations will give the same response, it is probably better to be pedantic, so I made the change.

Thanks @eric-murray

**Comment by ravindrapalaskar17** [comment]
Can we merge this PR..?

**Review by eric-murray — DISMISSED** [review]

**Review by eric-murray — APPROVED** [review]

**Pull request merged**
