### PR TITLE
fix: add missing "subscriptionId" in "RoamingStatus"-data for CloudEvent

### PR DESCRIPTION
**Pull request by maxl2287**
#### What type of PR is this?

Add one of the following kinds:
* correction

#### What this PR does / why we need it:
In the examples of callback CloudEvents for roaming-status, there is the subscriptionId given, but not in the corresponding component.
This will be fixed with this PR.

### CODE REVIEW

**Review by bigludo7 — APPROVED** [review]
Good Catch !

**Comment by sachinvodafone** [comment]
Hi @maxl2287 , It appears that this pull request aims to address two issues. First, correcting the device object where the country code was incorrectly placed under the device object. Second, ensuring that the country name is represented as an array, not a string, in the callback event . As per my understanding, It does not involve adding or amending the subscription field, as indicated in the request description, am i correct ?

**Comment by maxl2287** [comment]
@sachinvodafone you're right!
That fixes with the country-code came in caused by the previous PR: #106

**Review by bigludo7 — DISMISSED** [review]
LGTM

**Review by akoshunyadi — DISMISSED** [review]

**Comment by fernandopradocabrillo** [comment]
Just one comment here. Shouldn't this be a fix? instead of going in the v0.6.0-wip, couldn't we include it in a v0.5.1?

@maxl2287 @bigludo7 @akoshunyadi

**Comment by maxl2287** [comment]
> > Just one comment here. Shouldn't this be a fix? instead of going in the v0.6.0-wip, couldn't we include it in a v0.5.1?
> > @maxl2287 @bigludo7 @akoshunyadi
> 
> any thoughts? Once a team starts to implement the 0.5.0 version it's going to be obvious that there is a bug and I don't think that waiting to release a 0.6.0 is the best option. wdyt?
> 
> @maxl2287 @bigludo7 @akoshunyadi

I aggree.

@bigludo7 @akoshunyadi what about 0.5.1-wip ?

**Comment by akoshunyadi** [comment]
The general idea in Camara is to make more -smaller- releases, so 0.6.0 should come quite soon, I would say. But I don't have any objection, if somebody needs a 0.5.1 even sooner.

**Review by bigludo7 — APPROVED** [review]
Good for me. Thanks

**Comment by akoshunyadi** [comment]
I'll create an issue for 0.5.1, where we can discuss and define the content of it.

**Pull request merged**
