### PR TITLE
Prepare release r1.2 for M4 of CAMARA Fall24 release

### PR DESCRIPTION
**Pull request by akoshunyadi**
#### What type of PR is this?

* subproject management

#### What this PR does / why we need it:

Prepare the release r1.2 for M4 of the CAMARA Fall24 release.

### CODE REVIEW

**Comment by bigludo7** [comment]
Look very good - Thanks @akoshunyadi 

We need to add @hdamker in the loop for a check before to add release management as reviewer.

**Comment by hdamker** [comment]
> We need to add @hdamker in the loop for a check before to add release management as reviewer.

@bigludo7 thanks, but actually I'm acting here more on behalf of the RM team.

@akoshunyadi Looks good to me, except the README section "Release Information". You know left no information at all here. What other APIs have done:
* keeping information about the latest public release with the list of APIs and the direct links
* followed by two lines:

```
* Other releases of this repository are available in https://github.com/camaraproject/§repo_name§/releases
* For changes see [CHANGELOG.md](https://github.com/camaraproject/§repo_name§/blob/main/CHANGELOG.md)
```
An example you can find in [release PR of HomeDeviceQod](https://github.com/camaraproject/HomeDevicesQoD/pull/70/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5).

Alternative (if you don't want to have the latest release mentioned) - but then the four APIs are not mentioned in  the README:
```
* The latest release is available in https://github.com/camaraproject/§repo_name§/releases/latest
* Other releases and pre-release are available in https://github.com/camaraproject/§repo_name§/releases
* For changes see [CHANGELOG.md](https://github.com/camaraproject/§repo_name§/blob/main/CHANGELOG.md)
```

**Comment by hdamker** [comment]
> @hdamker actually the latest release line is still there, I only removed the block with the latest prerelease

ah, yes, it was int he collapsed part before the "note" - fine for me

**Comment by akoshunyadi** [comment]
All PRs have been merged, this PR has been updated. Kindly requesting final reviews @bigludo7 @sachinvodafone @camaraproject/release-management_maintainers

**Comment by bigludo7** [comment]
Great works @akoshunyadi 
One small comment, probably the checklist should be aligned with https://github.com/camaraproject/ReleaseManagement/blob/main/documentation/API-Readiness-Checklist.md meaning that we should have the magic sentences down and link.

Not a blocker for me but for global consistency.

**Comment by akoshunyadi** [comment]
@bigludo7 actually I removed that filling aid because I thought it's only for the first editor... this is what I saw in some other subprojects e.g. DeviceLocation
The Note and the link to the template are still there.

**Review by bigludo7 — APPROVED** [review]
LGTM !
Thanks for the hard work

**Review by sachinvodafone — APPROVED** [review]

**Comment by shilpa-padgaonkar** [comment]
One small point: I did not find this text https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#appendix-a-infodescription-template-for-device-identification-from-access-token in the spec files.

**Comment by akoshunyadi** [comment]
> One small point: I did not find this text https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#appendix-a-infodescription-template-for-device-identification-from-access-token in the spec files.

Done.

**Comment by soadeyemo** [comment]
All now OK. LGTM from release mgmt.

**Comment by tanjadegroot** [comment]
> @bigludo7 actually I removed that filling aid because I thought it's only for the first editor... this is what I saw in some other subprojects e.g. DeviceLocation The Note and the link to the template are still there.

@akoshunyadi I think the comment was that the API-Readiness-Checklist.md should have the actual clickable links in the table, rather than just text. Something to take that up for the next release.

**Pull request merged**
